### ISSUE TITLE
关于节奏风暴机制

### ISSUE THREAD

**Issue by lzghzr** [bilive/bilive_client#115]
目前节奏风暴抽奖为 帐号概率+时效
具体到某一个账号, 表现为

帐号是否有抽奖资格, 奖池是否仍有奖品, 帐号抽奖概率, 是否获得奖品

* 账号需要绑定手机才有资格
* 一个节奏风暴大概23秒抢光
* 一个账号如果从未抽奖, 且为活跃账号, 将会有大概率获得奖品
  * 被小黑屋无法获得奖品
  * 经常参与节奏风暴无法获得奖品
  * 某些账号永远不会获得奖品, 细节未知
  * 上一条的账号有部分会免疫黑屋, 也就是除了节奏风暴其他抽奖不会被小黑屋

对于小黑屋和被限制概率的账号, 可以使用暴力发包的方式参与
这种方法在几个月前只要20多次就可以保证90%, 目前概率已经大大降低

除了第一种没有参与资格的和第二种过了时间的
其余未中奖的都会提示错过了奖励, 真正错过奖励的会提示节奏风暴不存在

**Comment by yx1319250478** [comment]
今天突然发现参与节奏风暴的请求返回信息变了,之前是不存在,今天变参数错误了.不知道什么原因,是不是官方的返回信息变了

**Comment by Vector000** [comment]
B站节奏风暴api的变化，需要提交房间号才能参加抽奖，可以等大佬更新一波

发送自 Windows 11 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yx1319250478 <notifications@github.com>
发送时间: Thursday, January 3, 2019 4:04:59 PM
收件人: lzghzr/bilive_client
抄送: Subscribed
主题: Re: [lzghzr/bilive_client] 关于节奏风暴机制 (#115)


今天突然发现参与节奏风暴的请求返回信息变了,之前是不存在,今天变参数错误了.不知道什么原因,是不是官方的返回信息变了

―
