### ISSUE TITLE
特性请求：抽奖分类设置丢奖概率 and more

### ISSUE THREAD

**Issue by Skimige** [bilive/bilive_client#116]
rt
除题目外，还希望能有一个在网页端重启服务的功能…
因为手机没法远程控制 qvq

**Comment by lzghzr** [comment]
这样的话, 设置看起来会很多, 我倒是不介意这样

**Comment by fs779** [comment]
手机上下载个termux就可以ssh登录服务器了

**Comment by Skimige** [comment]
> 手机上下载个termux就可以ssh登录服务器了

服务器是运行在手机上的 Termux，想不到吧！x

**Comment by fs779** [comment]
哇，那是个什么操作_(:з」∠)_

**Comment by Skimige** [comment]
@lzghzr 话说我想写点废话 wiki 讲一下怎么在 Android 手机上 利用 Termux 跑这个项目从而实现闲置手机发光发热（x

**Comment by fs779** [comment]
哈哈哈，有想法鸭，如果想另一台手机ssh登录termux其实只要开启服务端功能，并用使用密匙登录好像也可以哇⊙∀⊙！

**Comment by Vector000** [comment]
Termux跑这个有的时候网络不行就很麻烦，而且手机的网络基本上是告别了`bilive_server`这个项目，我也只是之前树莓派断电的时候用来应过急，最好还是用云服务器跑
关于分类丢奖概率，我倒是搞了个每日抽奖限制，可以配合食用xD

**Comment by Skimige** [comment]
不过 手机跑的玄学加成大概就是家宽，云服务器容易被 IP 拉闸（雾
server 当然用云跑了x

**Comment by lzghzr** [comment]
所以你们都是自己跑 `bilive_server` 的吗

**Comment by Vector000** [comment]
我是有阿里云所以顺便自己跑了一个，延时会低一些
但是本地端的小号都是用的大佬的wss，校园网/家用宽带/移动网络wss多发监听就是个噩梦

**Comment by cris3980** [comment]
可以实现不同账号使用不同区域代理吗？

**Comment by lzghzr** [comment]
目前无此功能，也没有开发的打算。关于代理推荐使用第三方工具

发件人: cris3980
发送时间: 2月25日星期一 23:50
主题: Re: [lzghzr/bilive_client] 特性请求：抽奖分类设置丢奖概率 and more (#116)
收件人: lzghzr/bilive_client
抄送: lzzr, Mention


可以实现不同账号使用不同区域代理吗？
―
