### ISSUE TITLE
主站投币问题

### ISSUE THREAD

**Issue by qiumocanxue** [bilive/bilive_client#122]
(node:4208) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at MainSite._getVideoList (C:\Users\Administrator\Desktop\bilive_client-master\build\bilive\plugins\mainSite\index.js:80:48)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:4208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4208) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at MainSite._getVideoList (C:\Users\Administrator\Desktop\bilive_client-master\build\bilive\plugins\mainSite\index.js:80:48)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:4208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by Vector000** [comment]
主站投币优化 在做了 咕咕咕

**Comment by StringKe** [comment]
@Vector000 我有个账号在开启的时候 log 的状态是 未封禁 过一会后 Server酱推送被封禁，我重写开启这个账号是 输出未封禁 然后 Server 告诉我封了

**Comment by Vector000** [comment]
封禁状态没有用文件存储，每次重开之后会重设为未封禁状态。你再抽一次奖如果进去了的话就又是已封禁了

发送自 Windows 11 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: StringKe <notifications@github.com>
发送时间: Thursday, January 31, 2019 1:34:13 PM
收件人: lzghzr/bilive_client
抄送: Vector000; Mention
主题: Re: [lzghzr/bilive_client] 主站投币问题 (#122)


@Vector000<https://github.com/Vector000> 我有个账号在开启的时候 log 的状态是 未封禁 过一会后 Server酱推送被封禁，我重写开启这个账号是 输出未封禁 然后 Server 告诉我封了

―

**Comment by Vector000** [comment]
其实这个是因为Token过期了，导致登录状态失效，跟新commit其实没啥关系2333重开就好了

发送自 Windows 11 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: StringKe <notifications@github.com>
发送时间: Saturday, February 2, 2019 3:23:17 PM
收件人: lzghzr/bilive_client
抄送: Vector000; Mention
主题: Re: [lzghzr/bilive_client] 主站投币问题 (#122)


@Vector000<https://github.com/Vector000>
[image]<https://user-images.githubusercontent.com/31089228/52161318-591afb80-26fe-11e9-87bf-cfa53e08b46c.png>
这是您最新的一次推送，我看到你标注的commit为test所以把这个反馈给您

―

**Comment by StringKe** [comment]
@Vector000 我这里有遇到隔天应援团没有自动签到的问题，暂时还无法复现

**Comment by lovezm** [comment]
另外最近好像账号掉线后  不会刷新cookie了  要关闭 再开启
