### ISSUE TITLE
更新至2.0.1之后server chan收不到日常推送的问题

### ISSUE THREAD

**Issue by Naexen** [bilive/bilive_client#130]
各种重试没有发现解决方案(・_ゝ・)

**Comment by Vector000** [comment]
我有遇到过，结果发现是我的ip被serverChan的防火墙拦了，等了一天才好
可以上去它的网站做个测试，看看能不能收到信息

发送自 Windows 11

________________________________
发件人: Naexen <notifications@github.com>
发送时间: Tuesday, April 16, 2019 10:17:44 PM
收件人: lzghzr/bilive_client
抄送: Subscribed
主题: [lzghzr/bilive_client] 更新至2.0.1之后server chan收不到日常推送的问题 (#130)


各种重试没有发现解决方案(・_ゝ・)

**Comment by ff98sha** [comment]
> 我有遇到过，结果发现是我的ip被serverChan的防火墙拦了，等了一天才好 可以上去它的网站做个测试，看看能不能收到信息 
> […](#)

有相同问题，系统是win64，在关闭用户挂机时可以收到提示，但没有日常推送

**Comment by ShmilyChen** [comment]
> > 我有遇到过，结果发现是我的ip被serverChan的防火墙拦了，等了一天才好 可以上去它的网站做个测试，看看能不能收到信息
> > […](#)
> 
> 有相同问题，系统是win64，在关闭用户挂机时可以收到提示，但没有日常推送

这两天是因为方糖被人恶意举报了，具体可去server酱官网看

**Comment by ff98sha** [comment]
> > > 我有遇到过，结果发现是我的ip被serverChan的防火墙拦了，等了一天才好 可以上去它的网站做个测试，看看能不能收到信息
> > > […](#)
> >
> > 有相同问题，系统是win64，在关闭用户挂机时可以收到提示，但没有日常推送
> 这两天是因为方糖被人恶意举报了，具体可去server酱官网看

并不是，从几个月前开始就这样了，只有停止挂机的通知，没有日常汇报。

**Comment by lzghzr** [comment]
这是一个已知bug，并且被修复了，不过我不记得修复以后是否重新发布了release

**Comment by ff98sha** [comment]
没发release，最新的2.0.1是有这个问题的

**Comment by ShmilyChen** [comment]
> 没发release，最新的2.0.1是有这个问题的

Q：对发送消息有什么限制？

A：每人每天发送上限500条，相同内容5分钟内不能重复发送，不同内容10秒内不能连续发送 不同内容一分钟只能发送30条。主要是防止程序出错的情况。由于很多死循环请求导致服务器费用飙升，24小时请求接口超过1000次的账户将被封禁。


可不可能是因为这个（感觉不大可能）
