### ISSUE TITLE
有些问题想请教一下

### ISSUE THREAD

**Issue by 1604589485** [bilive/bilive_client#133]
May 24 2019 21:40:59 : 正在测试可用ip
May 24 2019 21:41:02 : 可用ip数量为 49
May 24 2019 21:41:07 : 已监听 :10080
May 24 2019 21:41:07 : 2 每日签到 已签到
May 24 2019 21:41:08 : 2 每日签到 已获取每日包裹
May 24 2019 21:41:08 : 1 每日签到 已获取每日包裹
May 24 2019 21:41:08 : 2 每日任务 { code: 65530,
  msg: 'invalid request',
  message: 'invalid request',
  data: 'bad token' }
May 24 2019 21:41:08 : 2 银瓜子兑换硬币 成功兑换 1 个硬币
May 24 2019 21:41:08 : 1 每日任务 { code: 65530,
  msg: 'invalid request',
  message: 'invalid request',
  data: 'bad token' }

然后去那个网页去设置http://github.halaal.win/bilive_client/#path=ws://localhost:10080&protocol=admin  结果网页显示404 挂ssr 也显示不出来  但是还是能抢到辣条

**Comment by lzghzr** [comment]
恩，因为转移了仓库，还没配置设置页
________________________________

**Comment by lzghzr** [comment]
已解决
