### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by s1073700227** [bilive/bilive_client#138]
C:\Users\Administrator\bilive_client>npm start

> bilive_client@2.0.4 start C:\Users\Administrator\bilive_client
> node build/app.js

(node:2512) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, scandir 'C:\Users\Administrator\bilive_client\build\bilive\plugins'
(node:2512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:2512) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by lzghzr** [comment]
哦，昨天更新的去除了所有插件，忘了加个空目录了
________________________________
