### ISSUE TITLE
设置页面只有总开关

### ISSUE THREAD

**Issue by s1073700227** [bilive/bilive_client#139]
其余小电视抽奖什么的开关都无

**Comment by lzghzr** [comment]
https://github.com/bilive/bilive_client/wiki/%E6%8F%92%E4%BB%B6%E5%88%97%E8%A1%A8

**Comment by s1073700227** [comment]
放入bilive_client\bilive\plugins并没有进行加载 还需要输入什么命令吗

**Comment by lzghzr** [comment]
如果你是自己编译的就再编译一遍
________________________________

**Comment by lzghzr** [comment]
或者你直接放在build/bilive_client/bilive/plugins也行
