### ISSUE TITLE
新活动要定向的直播间观看

### ISSUE THREAD

**Issue by xianyunb** [bilive/bilive_client#141]
新活动机甲要观看固定的直播间

**Comment by xianyunb** [comment]
会更新相关的插件吗

**Comment by lzghzr** [comment]
不知道是否和铃音挂机一致，是的话，目前还没破解出签名算法
________________________________

**Comment by yjqiang** [comment]
> 新活动机甲要观看固定的直播间

有网址么，我没看到。。。😀
