### ISSUE TITLE
UL等级

### ISSUE THREAD

**Issue by cris3980** [bilive/bilive_client#142]
不知道是不是昨天B站升级了，UL在线经验挂不到了

**Comment by lzghzr** [comment]
恩，我试了一下app观看也没加经验
________________________________

**Comment by Vector000** [comment]
心跳API又更新了？

发送自 Windows 11

________________________________
发件人: lzghzr <notifications@github.com>
发送时间: Sunday, July 7, 2019 6:54:02 PM
收件人: bilive/bilive_client
抄送: Subscribed
主题: Re: [bilive/bilive_client] UL等级 (#142)

恩，我试了一下app观看也没加经验
________________________________

**Comment by lzghzr** [comment]
> 心跳API又更新了？ 

可能不是老爷

**Comment by cris3980** [comment]
我重新弄了Vector000的分支正常了

**Comment by QHDS** [comment]
貌似没更新吧，我今天的双端用原来的api还正常，更新了应该就GG了

**Comment by cris3980** [comment]
可能是我下到上次活动未验证的api的锅吧，前几天才发现的，抽奖什么的都很正常

**Comment by lzghzr** [comment]
居然是这样嘛，难道新版app不能加经验了？
________________________________

**Comment by cris3980** [comment]
这个我倒是没观察过

**Comment by yjqiang** [comment]
@cris3980 你的意思是使用 Vector000 的分支，用户在不是老爷的情况下还能心跳❤️加经验么？
