### ISSUE TITLE
本地监听的用处

### ISSUE THREAD

**Issue by Fader10** [bilive/bilive_client#146]
我看到基础设置的左上角有一个本地监听，不知道是干什么用的，是在本地运行弹幕服务器吗

**Comment by lzghzr** [comment]
不是，可以用来设置监听端口或者domain socket
以及被拿来当password的用的protocol
________________________________

**Comment by Fader10** [comment]
那开不开对运行有影响吗

**Comment by lzghzr** [comment]
影响的是Web API监听，比如你需要Nginx反代或许需要改这个东西
________________________________
