### ISSUE TITLE
自动签到的接口已下线

### ISSUE THREAD

**Issue by aaa1115910** [bilive/bilive_client#148]
![QQ截图20190808113347](https://user-images.githubusercontent.com/34527143/62673391-df2b3e00-b9d0-11e9-8b09-d6849caae608.png)

**Comment by QHDS** [comment]
[sign.zip](https://github.com/bilive/bilive_client/files/3479758/sign.zip)

替换掉bilive\build\bilive\plugins\C_sign-master内index.js文件即可
