### ISSUE TITLE
现在礼物监听不到了吗

### ISSUE THREAD

**Issue by yx1319250478** [bilive/bilive_client#152]
完成每日任务之后，日志没看到关于礼物的监控了

**Comment by lzghzr** [comment]
只影响节奏风暴和舰队，其他不影响

**Comment by indefined** [comment]
广播服务器端那边11月11到期已经提醒了好几个月了，而且本地监听没猜错的话应该也是全部收不到了，现在弹幕服务器已经不发送`SYS_MSG | SYS_GIFT`类型消息了，所有广播消息都用`NOTICE_MSG`，所以之前广播消息的监控已经废了。不过这改动应该有段时间了，广播服务端用的同一套监听代码应该也会不能用才对，或者可能这个改动并没有全面生效，不过早晚肯定是全部取消用`NOTICE_MSG`的

**Comment by lzghzr** [comment]
只影响节奏风暴和舰队，其他不影响

> 广播服务器端那边11月11到期已经提醒了好几个月了，而且本地监听没猜错的话应该也是全部收不到了，现在弹幕服务器已经不发送`SYS_MSG | SYS_GIFT`类型消息了，所有广播消息都用`NOTICE_MSG`，所以之前广播消息的监控已经废了。不过这改动应该有段时间了，广播服务端用的同一套监听代码应该也会不能用才对，或者可能这个改动并没有全面生效，不过早晚肯定是全部取消用`NOTICE_MSG`的

因为一直能用，我就没管，原来已经改了吗

**Comment by indefined** [comment]
> 因为一直能用，我就没管，原来已经改了吗

昨天监听了一下弹幕确实没看到`SYS_MSG | SYS_GIFT`消息了，我也有段时间没挂了不知道什么时候改的，不过反正也懒得挂了所以我也没去动它

**Comment by Billyzou0741326** [comment]
礼物提醒全部归入`NOTICE_MSG`了好像

**Comment by lzghzr** [comment]
> 礼物提醒全部归入`NOTICE_MSG`了好像

恩，我有时间去看看
