### ISSUE TITLE
启动的问题

### ISSUE THREAD

**Issue by s-199** [bilive/bilive_client#153]
大大你好，我重下文件跑完数据后启动发现连不上服务器，在index里修改了和options都修改了ws还是不行，但在index的显示日志页面却有我保存的用户在抽奖（没有启动bilive）见鬼了

**Comment by lzghzr** [comment]
没看懂描述，是自己搭了server连不上吗

**Comment by s-199** [comment]
> 没看懂描述，是自己搭了server连不上吗

啊 我的确有搭过监听但貌似我没没连过，start后好像提示服务器ip连接不上之类的吧

**Comment by tea-rain** [comment]
我也是,怎么也连不上服务器了,还以为是我的问题...

**Comment by s-199** [comment]
我弄好啦 重启后跑了遍分支Thanks♪(･ω･)ﾉ
