### ISSUE TITLE
如何制作Release

### ISSUE THREAD

**Issue by ShmilyChen** [bilive/bilive_client#156]
请问下，bilive系列的如何打包Release啊

**Comment by lzghzr** [comment]
编译之后在build里加入`package.json`文件, 执行安装
再把node.exe放进去就行了

插件可以单独编译或者直接下载后放到`build/bilive/plugins`里

**Comment by ShmilyChen** [comment]
我有个插件请问怎么提供给你啊？？？
自动参与lpl系列抽奖
[autoActTask.zip](https://github.com/bilive/bilive_client/files/4342899/autoActTask.zip)

**Comment by lzghzr** [comment]
> 我有个插件请问怎么提供给你啊？？？
> 自动参与lpl系列抽奖
> [autoActTask.zip](https://github.com/bilive/bilive_client/files/4342899/autoActTask.zip)

在GitHub上创建项目再转移到 [bilive](https://github.com/bilive), 或者我邀请你进 [bilive](https://github.com/bilive) 再创新项目

**Comment by ShmilyChen** [comment]
我看到个叫做ncc的插件能把nodejs项目，能直接快速打包成一个index.js文件，大佬有考虑做一下吗？
