### ISSUE TITLE
链接多次自动关闭

### ISSUE THREAD

**Issue by a08381** [bilive/bilive_client#157]
![Snipaste_2020-03-12_13-33-03](https://user-images.githubusercontent.com/2505002/76490476-33663700-6466-11ea-8183-5242e39b09d4.png)

个人感觉可能是nginx配置有问题

nginx的配置文件我上传到[这里](https://pastebin.com/tPY5TRZa)了

**Comment by lzghzr** [comment]
没看出什么问题, 可能是网络不太好, 心跳包没发出去
