### ISSUE TITLE
0418版本报错：appStatus is not defined

### ISSUE THREAD

**Issue by LoidVC** [bilive/bilive_client#160]
Apr 19 2020 00:13:07 : Cookie已失效
(node:3484) UnhandledPromiseRejectionWarning: ReferenceError: appStatus is not defined
    at Online.refresh (C:\Users\Administrator\m\bilive_client\build\bilive\lib\tv_client.js:102:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ShmilyChen** [comment]
`bilive\lib\tv_client.ts`这个文件里面添加
```
enum appStatus {
  'success',
  'captcha',
  'error',
  'httpError',
}
```
![image](https://user-images.githubusercontent.com/34965399/79642974-17775300-81d3-11ea-8451-774f8c4b8e52.png)

**Comment by LoidVC** [comment]
> `bilive\lib\tv_client.ts`这个文件里面添加
> 
> ```
> enum appStatus {
>   'success',
>   'captcha',
>   'error',
>   'httpError',
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/34965399/79642974-17775300-81d3-11ea-8451-774f8c4b8e52.png)
> 
> 然后重新编译

谢谢
