### ISSUE TITLE
设置界面只有总开关

### ISSUE THREAD

**Issue by LoidVC** [bilive/bilive_client#161]
0419版本运行以后，设置界面只有总开关...Wiki和本地的设置都试过，这是我的问题吗？

**Comment by lzghzr** [comment]
默认不包含任何插件

**Comment by LoidVC** [comment]
请问安装插件后编译报错怎么办？

  build/plugins/C_treasureBox/index.ts:20:16
    20   public async load({ defaultOptions, whiteList }: { defaultOptions: opti
ons, whiteList: Set<string> }) {
                      ~~~~
    'load' is declared here.


Found 33 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bilive_client@2.1.1 build:client: `tsc -p tsconfig.json && npm-run-posi
x-or-windows copy:client`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bilive_client@2.1.1 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-20T1
7_32_18_350Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bilive_client@2.1.1 build: `npm run build:client && npm run build:view`

npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bilive_client@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-20T1
7_32_18_397Z-debug.log

**Comment by LoidVC** [comment]
> 请问安装插件后编译报错怎么办？
> 
> build/plugins/C_treasureBox/index.ts:20:16
> 20 public async load({ defaultOptions, whiteList }: { defaultOptions: opti
> ons, whiteList: Set }) {
> ~~~~
> 'load' is declared here.
> 
> Found 33 errors.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! bilive_client@2.1.1 build:client: `tsc -p tsconfig.json && npm-run-posi x-or-windows copy:client`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the bilive_client@2.1.1 build:client script.
> npm ERR! This is probably not a problem with npm. There is likely additional log
> ging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2020-04-20T1
> 7_32_18_350Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! bilive_client@2.1.1 build: `npm run build:client && npm run build:view`
> 
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the bilive_client@2.1.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional log
> ging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2020-04-20T1
> 7_32_18_397Z-debug.log

明白了，插件得放build里面。。。
