### ISSUE TITLE
请求恢复主站插件

### ISSUE THREAD

**Issue by LoidVC** [bilive/bilive_client#163]
之前看到有主站插件，可以播放、分享、投币的，希望能加上~

**Comment by LoidVC** [comment]
然后...希望风暴能设置参数，比如间隔、次数~

**Comment by lzghzr** [comment]
主站插件作者 @Vector000  也可以到[他的分支](https://github.com/Vector000/bilive_client)里复制过来

**Comment by LoidVC** [comment]
> 主站插件作者 @Vector000 也可以到[他的分支](https://github.com/Vector000/bilive_client)里复制过来

感谢，但看了一下Vector000那边的插件没有index.js文件，请问是不能通用吗？

**Comment by LoidVC** [comment]
方便的话能否麻烦看看Vector的风暴和主站如何拿过来用...投币和多次参与风暴挺有用orz

**Comment by lzghzr** [comment]
> 感谢，但看了一下Vector000那边的插件没有index.js文件，请问是不能通用吗？

因为没提供js文件, 需要自己编译

**Comment by LoidVC** [comment]
去Vector那边编译以后复制过来了，主站可用，但抽奖不可用，报错如下：
`Apr 23 2020 00:46:51 : 已加载: 主站功能, 用于: 每天自动做主站功能（观看、分享、
投币）, 版本: 0.0.5, 作者: Vector000
(node:3180) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'st
ormSetting' of undefined
    at Raffle.load (C:\Users\Administrator\m\bilive_client\build\bilive\plugins\
raffle\index.js:39:50)
    at BiLive._loadPlugin (C:\Users\Administrator\m\bilive_client\build\bilive\i
ndex.js:92:30)
(node:3180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:3180) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`
请问怎么处理？

**Comment by lzghzr** [comment]
> 去Vector那边编译以后复制过来了，主站可用，但抽奖不可用，报错如下：
> `Apr 23 2020 00:46:51 : 已加载: 主站功能, 用于: 每天自动做主站功能（观看、分享、 投币）, 版本: 0.0.5, 作者: Vector000 (node:3180) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'st ormSetting' of undefined at Raffle.load (C:\Users\Administrator\m\bilive_client\build\bilive\plugins\ raffle\index.js:39:50) at BiLive._loadPlugin (C:\Users\Administrator\m\bilive_client\build\bilive\i ndex.js:92:30) (node:3180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) (node:3180) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre cated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> 请问怎么处理？

看起来是作者加了私有属性, 可能需要稍微修改一下才能用

**Comment by ShmilyChen** [comment]
> > 去Vector那边编译以后复制过来了，主站可用，但抽奖不可用，报错如下：
> > `Apr 23 2020 00:46:51 : 已加载: 主站功能, 用于: 每天自动做主站功能（观看、分享、 投币）, 版本: 0.0.5, 作者: Vector000 (node:3180) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'st ormSetting' of undefined at Raffle.load (C:\Users\Administrator\m\bilive_client\build\bilive\plugins\ raffle\index.js:39:50) at BiLive._loadPlugin (C:\Users\Administrator\m\bilive_client\build\bilive\i ndex.js:92:30) (node:3180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) (node:3180) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre cated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> > 请问怎么处理？
> 
> 看起来是作者加了私有属性, 可能需要稍微修改一下才能用

v0分支的部分设置是放到了高级设置里面，你的分支里面没有这个东西

**Comment by lzghzr** [comment]
https://github.com/bilive/C_mainSite
