### ISSUE TITLE
对请求函数进行并发控制

### ISSUE THREAD

**Issue by ShmilyChen** [bilive/bilive_client#164]
我上次百度上看到async 可以限制并发，最近好像破站的请求都很容易风控，建议大佬加一个并发控制

**Comment by lzghzr** [comment]
之前考虑过，后来发现并不是所有API都有限制，有些一直访问也不会出错，就放弃了

**Comment by lovezm** [comment]
破站已经开始412风控了。

**Comment by lzghzr** [comment]
应该只是抽奖有限制, 所以在[抽奖插件](https://github.com/bilive/C_raffle)加了队列, 试了几天应该没什么问题
