### ISSUE TITLE
新黑屋

### ISSUE THREAD

**Issue by ShmilyChen** [bilive/bilive_client#168]
破站好像开始分离黑屋了，我领取宝箱是访问被拒绝，但是能够正常进行抽奖，扭蛋也能正常抽取

**Comment by lzghzr** [comment]
确实如此, 一直抽奖好像也没什么问题

**Comment by ShmilyChen** [comment]
大佬想想办法，看看能不能规避下宝箱黑屋

**Comment by lzghzr** [comment]
应该没什么好办法，即使是浏览器脚本自动领宝箱都会进黑屋，我想不到更安全的方法了

**Comment by ShmilyChen** [comment]
猜测，可能是同ip同时领取的数量？
