### ISSUE TITLE
关于违规使用软件在直播间抢辣条的处罚公告

### ISSUE THREAD

**Issue by lzghzr** [bilive/bilive_client#170]
### [关于违规使用软件在直播间抢辣条的处罚公告](https://link.bilibili.com/p/eden/news#/newsdetail?id=1229)

&emsp;&emsp;近期收到用户反馈有用户通过非法手段参与直播间抢辣条行为。该方式严重影响了直播间氛围，破坏了正常用户的体验。因此，哔哩哔哩直播在此严正声明：
&emsp;&emsp;禁止用户使用第三方软件（包括但不限于机器人软件、蜘蛛软件、爬虫软件等任何自动程序、脚本、软件）在直播间抢辣条等违规行为，根据《哔哩哔哩弹幕网用户使用协议》，对使用违规手段的用户哔哩哔哩有权进行违规数据清除，严重者将封禁账号，近期我们会加强对这方面的监控和处理。
&emsp;&emsp;感谢所有用户对哔哩哔哩直播一直以来的理解和支持，让我们共建公平和谐的直播环境。

**Comment by Naexen** [comment]
处罚结果:不掉辣条了(x

**Comment by lzghzr** [comment]
> 处罚结果:不掉辣条了(x

氪金 白嫖 从此阴阳两隔
