### ISSUE TITLE
恭喜哔哩哔哩直播进入新时代

### ISSUE THREAD

**Issue by lzghzr** [bilive/bilive_client#172]
### [哔哩哔哩直播功能升级公告](https://link.bilibili.com/p/eden/news#/newsdetail?id=1309)

![p](https://i0.hdslb.com/bfs/vc/f37efa6e3a7fc0fb91a88cba4fe94670f95064eb.png)

**Comment by BanqiJane** [comment]
lzghzr大大会对此做相应的更新吗

**Comment by lzghzr** [comment]
> lzghzr大大会对此做相应的更新吗

没啥可更新的了吧，明显就是白嫖用户滚出去，挂机也没什么意义了

**Comment by ShmilyChen** [comment]
20级勋章送礼还不加亲密度

**Comment by BanqiJane** [comment]
> 20级勋章送礼还不加亲密度

没用了 这些年挂机升20级粉丝勋章的努力全白费了 一个舰长就可以获得21级勋章了

**Comment by HHHHhgqcdxhg** [comment]
大大继续维护啊你这是我的上游项目(´；ω；`)
