### ISSUE TITLE
设置页面为什么打不开

### ISSUE THREAD

**Issue by DoedKr** [bilive/bilive_client#174]
网页里的也试了，docs文件夹里的index也试了都是啥都没有，只有一片黑。

**Comment by lzghzr** [comment]
你是把jsdelivr屏蔽了吗

**Comment by DoedKr** [comment]
> 
> 
> 你是把jsdelivr屏蔽了吗

应该没有吧，咋确定是否屏蔽了

**Comment by DoedKr** [comment]
> 
> 
> 你是把jsdelivr屏蔽了吗

 我直接打开了docs/index.html里边的css和js地址，没有问题能打开啊

**Comment by lzghzr** [comment]
同步了一份到码云, 你试一下能不能打开 http://bilive.gitee.io/bilive_client/

**Comment by DoedKr** [comment]
> 
> 
> 同步了一份到码云, 你试一下能不能打开 http://bilive.gitee.io/bilive_client/

结果一样，只有一个黑背景
IE edge Firefox三个浏览器全这样
想不明白到底是哪里的问题

**Comment by pjy612** [comment]
jsdelivr 前几天炸了吧？
