### ISSUE TITLE
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this check

### ISSUE THREAD

**Issue by cuihua0** [bilive/bilive_client#175]
Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.npm ERR! code ELIFECYCLE
npm ERR! errno 216
npm ERR! bilive_client@2.2.0 start: `node app.js`
npm ERR! Exit status 216
npm ERR!
npm ERR! Failed at the bilive_client@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lzghzr** [comment]
难道你还在用xp？

**Comment by cuihua0** [comment]
> 难道你还在用xp？

我用的win7，请问怎么解决？

**Comment by lzghzr** [comment]
> 我用的win7，请问怎么解决？

可以找低版本(需>12)的nodejs或者使用虚拟机

**Comment by cuihua0** [comment]
> 可以找低版本(需>12)的nodejs或者使用虚拟机
实际上我出现这个错误所下的版本是大于12的，node-v12.18.3-x64
虚拟机我会最后考虑，因为太占资源了

**Comment by cuihua0** [comment]
我需要用更低的版本吗？

**Comment by lzghzr** [comment]
> 我需要用更低的版本吗？
> 官网我只找到一个14版本和我现在这个，其它下载没有= =

低于v12无法运行, 没有办法, 毕竟win7已经停止支持, 各种软件也不会维护了

**Comment by cuihua0** [comment]
所以我现在要么用虚拟机要么不用吗？

**Comment by lzghzr** [comment]
> 所以我现在要么用虚拟机要么不用吗？

可以这么说

**Comment by cuihua0** [comment]
好的，谢谢你
