### ISSUE TITLE
设置网页打不开了

### ISSUE THREAD

**Issue by ruoxiaoqin** [bilive/bilive_client#176]
https://lzoczr.gitee.io/bilive_client_view/#path=ws://localhost:10080&protocol=admin显示404了，有没有可以打开的网页？
还有一个问题，怎么更新2.2版本？

**Comment by lzghzr** [comment]
https://github.com/bilive/bilive_client/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95(%E5%88%9D%E7%BA%A7)
