### ISSUE TITLE
更新后打不开

### ISSUE THREAD

**Issue by Azurlane-a** [bilive/bilive_client#180]
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\23826\Desktop\bilive_client\build\bilive\online.js:26:38)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@3.0.0 start: `node build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilive_client@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
2020-10-02T06_00_36_290Z-debug.log

log内容如下：
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bilive_client@3.0.0~prestart: bilive_client@3.0.0
6 info lifecycle bilive_client@3.0.0~start: bilive_client@3.0.0
7 verbose lifecycle bilive_client@3.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bilive_client@3.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\23826\Desktop\bilive_client\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;A:\Git\cmd;C:\Program Files\nodejs\;C:\Users\23826\Desktop\BiliHelper-personal-master\新建文件夹;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;A:\Git\cmd;C:\Program Files\nodejs\;C:\Users\23826\Desktop\BiliHelper-personal-master\新建文件夹;C:\ProgramData\ComposerSetup\bin;C:\Users\23826\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\23826\AppData\Local\Programs\Python\Python38-32\;C:\Users\23826\AppData\Local\Microsoft\WindowsApps;A:\Microsoft VS Code\bin;C:\Users\23826\AppData\Roaming\npm;C:\Users\23826\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\Java\jdk1.8.0_211\bin;A:\IntelliJ IDEA 2020.2\bin;
9 verbose lifecycle bilive_client@3.0.0~start: CWD: C:\Users\23826\Desktop\bilive_client
10 silly lifecycle bilive_client@3.0.0~start: Args: [ '/d /s /c', 'node build/app.js' ]
11 silly lifecycle bilive_client@3.0.0~start: Returned: code: 1  signal: null
12 info lifecycle bilive_client@3.0.0~start: Failed to exec start script
13 verbose stack Error: bilive_client@3.0.0 start: `node build/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bilive_client@3.0.0
15 verbose cwd C:\Users\23826\Desktop\bilive_client
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error bilive_client@3.0.0 start: `node build/app.js`
22 error Exit status 1
23 error Failed at the bilive_client@3.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

已反复在不同机子上测试 还是无法打开 已详细操作wiki使用方式里的每个步骤

**Comment by lzghzr** [comment]
应该是nodejs版本过低

**Comment by Azurlane-a** [comment]
> 应该是nodejs版本过低

谢谢大大 已解决
