### ISSUE TITLE
登陆崩溃

### ISSUE THREAD

**Issue by lunmx** [bilive/bilive_client#182]
程序报错：
const cookies = authResponseData.cookie_info.cookies;
                                                     
TypeError: Cannot read property 'cookies' of null

**Comment by lzghzr** [comment]
最近版本更新挺快的，我有时间再重新捋一下登录逻辑

**Comment by lzghzr** [comment]
登录崩溃是B站改了手机验证流程导致的，随便修一下就行，但为了以后少出现这种问题，还要加强这一部分的容错能力
